#!/usr/bin/env python

import locale
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))

from rlselectlib.config import Config
from rlselectlib.filter import search
from rlselectlib.interactive import UiController
from rlselectlib.reader import Lines


USAGE = """\
I select stuff.

Usage:
  {name} [--tab] [--action] [--gui] [--] [<initial-search-term>...]
  {name} (-h | --help)

Options:
  --tab         Allow <Tab> to select an item.
  --action      Print the action taken on the first line.
  --gui         Use GUI version instead of console version.
  -h,  --help   Show this message and exit.
""".format(
    name=os.path.basename(__file__)
)


def main():
    args = parse_args()
    if args["-h"] or args["--help"]:
        usage()
        success()
    locale.setlocale(locale.LC_ALL, "")
    system_encoding = locale.getpreferredencoding()
    input_encoding = system_encoding
    output_encoding = system_encoding
    (action, result) = get_ui_fn(args)(Config(), UiController(
        lines=Lines.from_stream(sys.stdin, input_encoding),
        term=(" ".join(args["<initial-search-term>"])).decode(
            system_encoding,
            "replace"
        ),
        search_fn=search,
        tab_exits=args["--tab"]
    ))
    if args["--action"]:
        print(action.name)
    if action.abort:
        fail()
    else:
        print(result.encode(output_encoding))
        success()


def get_ui_fn(args):
    if args["--gui"]:
        from rlselectlib.ui_wx import wx_ui_run
        return wx_ui_run
    else:
        from rlselectlib.ui_curses import curses_ui_run
        return curses_ui_run


def parse_args():
    args = {
        "-h": False,
        "--help": False,
        "--tab": False,
        "--action": False,
        "--gui": False,
        "<initial-search-term>": [],
    }
    rest = sys.argv[1:]
    if rest == ["-h"]:
        args["-h"] = True
        rest = []
    if rest == ["--help"]:
        args["--help"] = True
        rest = []
    while rest:
        if rest[:1] == ["--tab"]:
            args["--tab"] = True
            rest = rest[1:]
        if rest[:1] == ["--action"]:
            args["--action"] = True
            rest = rest[1:]
        elif rest[:1] == ["--gui"]:
            args["--gui"] = True
            rest = rest[1:]
        elif rest[:1] == ["--"]:
            args["<initial-search-term>"] = rest[1:]
            rest = []
        else:
            args["<initial-search-term>"] = rest
            rest = []
    return args


def usage():
    print(USAGE.strip())


def success():
    sys.exit(0)


def fail():
    sys.exit(1)


if __name__ == "__main__":
    main()
