#!/usr/bin/env python

import locale
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))

from selectlib.config import Config
from selectlib.encoding import to_unicode
from selectlib.filter import search
from selectlib.interactive import UiController
from selectlib.reader import Lines
from selectlib.terminal import output_to_prompt


USAGE = """\
I select stuff.

Usage:
  {name} [--complete] [--gui] [--] <initial-search-terms>...
  {name} (-h | --help)

Options:
  --complete    Run in complete mode:
                write result to console instead of stdout.
  --gui         Use GUI version instead of console version.
  -h,  --help   Show this message and exit.
""".format(
    name=os.path.basename(__file__)
)


def main():
    args = parse_args()
    if args["-h"] or args["--help"]:
        usage()
        success()
    locale.setlocale(locale.LC_ALL, "")
    (action, result) = get_ui_fn(args)(Config(), UiController(
        lines=Lines.from_stream(sys.stdin, locale.getpreferredencoding()),
        term=to_unicode(" ".join(args["<initial-search-terms>"])),
        search_fn=search,
        tab_exits=args["--complete"]
    ))
    if args["--complete"] and action == "tab":
        output_to_prompt(result)
        success()
    elif args["--complete"] and action == "select":
        output_to_prompt(result+"\n")
        success()
    elif not args["--complete"] and action == "select":
        print(result)
        success()
    fail()


def get_ui_fn(args):
    if args["--gui"]:
        from selectlib.ui_wx import wx_ui_run
        return wx_ui_run
    else:
        from selectlib.ui_curses import curses_ui_run
        return curses_ui_run


def parse_args():
    args = {
        "-h": False,
        "--help": False,
        "--complete": False,
        "--gui": False,
        "<initial-search-terms>": [],
    }
    rest = sys.argv[1:]
    if rest == ["-h"]:
        args["-h"] = True
        rest = []
    if rest == ["--help"]:
        args["--help"] = True
        rest = []
    while rest:
        if rest[:1] == ["--complete"]:
            args["--complete"] = True
            rest = rest[1:]
        elif rest[:1] == ["--gui"]:
            args["--gui"] = True
            rest = rest[1:]
        elif rest[:1] == ["--"]:
            args["<initial-search-terms>"] = rest[1:]
            rest = []
        else:
            args["<initial-search-terms>"] = rest
            rest = []
    return args


def usage():
    print(USAGE.strip())


def success():
    sys.exit(0)


def fail():
    sys.exit(1)


if __name__ == "__main__":
    main()
