#!/usr/bin/env python

import fcntl
import os
import sys
import termios

sys.path.insert(0, os.path.dirname(__file__))

from selectlib.filter import search
from selectlib.interactive import run_curses
from selectlib.reader import read

USAGE = """\
I select stuff.

Usage:
  {name} [--out (print | shell)]
  {name} (-h | --help)

Options:
  -h --help       Show this message and exit.
""".format(
    name=os.path.basename(__file__)
)

class CLI(object):

    def run(self):
        if "-h" in sys.argv or "--help" in sys.argv:
            self._usage()
            self._fail()
        (action, result) = run_curses(read(sys.stdin), "", search)
        if self._out_is("print") and action in ("select", "tab"):
            print(result)
            self._success()
        elif self._out_is("shell") and action == "tab":
            self._output_to_terminal(result.rstrip())
            self._success()
        elif self._out_is("shell") and action == "select":
            self._output_to_terminal(result.rstrip()+"\n")
            self._success()
        self._fail()

    def _output_to_terminal(self, text):
        for ch in text:
            fcntl.ioctl(sys.stdout.fileno(), termios.TIOCSTI, ch)

    def _out_is(self, value):
        return self._get_option("--out", "print") == value

    def _get_option(self, name, default):
        option_found = False
        for arg in sys.argv:
            if option_found:
                return arg
            if arg == name:
                option_found = True
        return default

    def _usage(self):
        print(USAGE.strip())

    def _success(self):
        sys.exit(0)

    def _fail(self):
        sys.exit(1)

CLI().run()
