#!/usr/bin/env python

import os
import sys

sys.path.insert(0, os.path.dirname(__file__))

from selectlib.filter import search
from selectlib.interactive import UiController
from selectlib.reader import read
from selectlib.terminal import output_to_prompt


USAGE = """\
I select stuff.

Usage:
  {name} [--out (print | shell)] [--gui]
  {name} (-h | --help)

Options:
  -h --help       Show this message and exit.
  --gui           Use GUI version.
""".format(
    name=os.path.basename(__file__)
)


def main():
    args = parse_args()
    if args["-h"] or args["--help"]:
        usage()
        success()
    (action, result) = get_ui_fn(args)(UiController(
        read(sys.stdin),
        "",
        search
    ))
    if args["--out"] == "print" and action in ("select", "tab"):
        print(result)
        success()
    if args["--out"] == "shell" and action == "tab":
        output_to_prompt(result)
        success()
    if args["--out"] == "shell" and action == "select":
        output_to_prompt(result+"\n")
        success()
    fail()


def get_ui_fn(args):
    if args["--gui"]:
        from selectlib.ui_wx import wx_ui_run
        return wx_ui_run
    else:
        from selectlib.ui_curses import curses_ui_run
        return curses_ui_run


def parse_args():
    args = {
        "-h": False,
        "--help": False,
        "--out": "print",
        "--gui": False,
    }
    rest = sys.argv[1:]
    if rest == ["-h"]:
        args["-h"] = True
        rest = []
    if rest == ["--help"]:
        args["--help"] = True
        rest = []
    while rest:
        if rest[:2] == ["--out", "print"]:
            args["--out"] = "print"
            rest = rest[2:]
        elif rest[:2] == ["--out", "shell"]:
            args["--out"] = "shell"
            rest = rest[2:]
        elif rest[:1] == ["--gui"]:
            args["--gui"] = True
            rest = rest[1:]
        else:
            usage()
            fail()
    return args


def usage():
    print(USAGE.strip())


def success():
    sys.exit(0)


def fail():
    sys.exit(1)


if __name__ == "__main__":
    main()
